version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Instalar dependencias
          command: pip install -r requirements.txt
      - run:
          name: Ejecutar tests
          command: python -m pytest test.py -v

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
